keys:
  - &personal-mbp age1f36mqstu7qyy29l36jwfdc6zqfxa6a3x543ly8025wk74gnstehqa7zdp8
  - &optimus age10w6h0zkf6wxu8pgjpgct45syuxh642t7u6xw6fkv284tdamn0asspjy2tz
  - &rpi4 age198n0gq77tcskc9yc0euw3j5jgnk4aaeq9xhfqh52dcd82egpf3tqgc2cmc
  - &rpi5 age1a4dsm6vg0qcl4jknktrvtvkva2z2dyjmm7guu8gsuxmnc5mw6q8sd335fp
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *personal-mbp
      - *optimus
      - *rpi4
      - *rpi5
